### ISSUE TITLE
Unable to run interactiveSim.py on Mac

### ISSUE THREAD

**Issue by toblaroni** [meshtastic/Meshtasticator#20]
I have been unable to run interactiveSim.py on Mac using Docker. ```python3 interactiveSim.py 3 -d``` gives me ```Tkinter is needed. Install python3-tk with your package manager.``` despite the fact the tkinter is installed on my machine.

**Comment by GUVWAF** [comment]
Can you try what `python3 -m tkinter` gives as output? 
I don't have much experience with a Mac, but it *should* just work after `brew install python-tk`.

**Comment by toblaroni** [comment]
`python3 -m tkinter` opens a little dialogue:

<img width="335" alt="Screenshot 2024-12-02 at 18 28 17" src="https://github.com/user-attachments/assets/3b75f121-e628-49c2-acc7-5fd32aa1e62c">

**Comment by GUVWAF** [comment]
Okay, that looks good. Then there might be another issue when calling `matplotlib.use("TkAgg")`. Can you check what that gives as output in a Python shell? 
Otherwise you can try replacing it by `matplotlib.use("Agg")`, but I'm not sure if all plotting will show correctly then.

**Comment by toblaroni** [comment]
`matplotlib.use("TkAgg")` has no output for me in a Python shell.

**Comment by GUVWAF** [comment]
Can you try to remove the `try` block here: 
https://github.com/meshtastic/Meshtasticator/blob/5e82f00c3d34e37dddfab8035000ab0087021f10/lib/common.py#L13-L17

And see what the output is.
Else, you could try to change it to `matplotlib.use("Agg")`.

**Comment by toblaroni** [comment]
The output when I remove the `try` block is:
```
Traceback (most recent call last):
  File "/Users/toblaroni/Documents/programming/meshtastic/Meshtasticator/interactiveSim.py", line 7, in <module>
    from lib.interactive import *
  File "/Users/toblaroni/Documents/programming/meshtastic/Meshtasticator/lib/interactive.py", line 14, in <module>
    from .common import *
  File "/Users/toblaroni/Documents/programming/meshtastic/Meshtasticator/lib/common.py", line 13, in <module>
    matplotlib.use("TkAgg")
    ~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/toblaroni/Documents/programming/meshtastic/Meshtasticator/venv/lib/python3.13/site-packages/matplotlib/__init__.py", line 1249, in use
    plt.switch_backend(name)
    ~~~~~~~~~~~~~~~~~~^^^^^^
  File "/Users/toblaroni/Documents/programming/meshtastic/Meshtasticator/venv/lib/python3.13/site-packages/matplotlib/pyplot.py", line 342, in switch_backend
    module = importlib.import_module(cbook._backend_module_name(newbackend))
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/toblaroni/Documents/programming/meshtastic/Meshtasticator/venv/lib/python3.13/site-packages/matplotlib/backends/backend_tkagg.py", line 1, in <module>
    from . import _backend_tk
  File "/Users/toblaroni/Documents/programming/meshtastic/Meshtasticator/venv/lib/python3.13/site-packages/matplotlib/backends/_backend_tk.py", line 25, in <module>
    from . import _tkagg
ImportError: Failed to load Tcl_SetVar
```

When i change it to `matplotlib.use("Agg")` i get:

```
Traceback (most recent call last):
  File "/Users/toblaroni/Documents/programming/meshtastic/Meshtasticator/interactiveSim.py", line 9, in <module>
    sim = interactiveSim() # Start the simulator
  File "/Users/toblaroni/Documents/programming/meshtastic/Meshtasticator/lib/interactive.py", line 325, in __init__
    self.graph = interactiveGraph()
                 ~~~~~~~~~~~~~~~~^^
  File "/Users/toblaroni/Documents/programming/meshtastic/Meshtasticator/lib/interactive.py", line 126, in __init__
    super().__init__()
    ~~~~~~~~~~~~~~~~^^
  File "/Users/toblaroni/Documents/programming/meshtastic/Meshtasticator/lib/common.py", line 313, in __init__
    move_figure(self.fig, 200, 200)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/Users/toblaroni/Documents/programming/meshtastic/Meshtasticator/lib/common.py", line 298, in move_figure
    fig.canvas.manager.window.wm_geometry("+%d+%d" % (x, y))
    ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FigureManagerBase' object has no attribute 'window'
```

**Comment by toblaroni** [comment]
Upgraded matplotlib to 3.9.3 and still getting the same `Tkinter is needed. Install python3-tk with your package manager.` error.

**Comment by GUVWAF** [comment]
Hmm, looks like it will only be in `matplotlib` v3.10.0...
Unless you’re able to install an older version of `python-tk` that uses a version of Tcl/Tk before 9.0, I don’t think it will work until `matplotlib` v3.10.0 is out.

**Comment by GUVWAF** [comment]
@toblaroni matplotlib v3.10.0 is out, can you try if that fixes your issue?

**Comment by toblaroni** [comment]
Thanks for your help, I'm no longer getting the tkinter error message.

**Comment by toblaroni** [comment]
I do however get a new error when running `python3 interactiveSim.py 3 -d`:

```Traceback (most recent call last):
  File "/Users/toblaroni/Documents/programming/meshtastic/Meshtasticator/venv/lib/python3.13/site-packages/docker/api/client.py", line 275, in _raise_for_status
    response.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/toblaroni/Documents/programming/meshtastic/Meshtasticator/venv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.47/containers/create?name=Meshtastic

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/toblaroni/Documents/programming/meshtastic/Meshtasticator/venv/lib/python3.13/site-packages/docker/models/containers.py", line 876, in run
    container = self.create(image=image, command=command,
                            detach=detach, **kwargs)
  File "/Users/toblaroni/Documents/programming/meshtastic/Meshtasticator/venv/lib/python3.13/site-packages/docker/models/containers.py", line 935, in create
    resp = self.client.api.create_container(**create_kwargs)
  File "/Users/toblaroni/Documents/programming/meshtastic/Meshtasticator/venv/lib/python3.13/site-packages/docker/api/container.py", line 440, in create_container
    return self.create_container_from_config(config, name, platform)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/toblaroni/Documents/programming/meshtastic/Meshtasticator/venv/lib/python3.13/site-packages/docker/api/container.py", line 457, in create_container_from_config
    return self._result(res, True)
           ~~~~~~~~~~~~^^^^^^^^^^^
  File "/Users/toblaroni/Documents/programming/meshtastic/Meshtasticator/venv/lib/python3.13/site-packages/docker/api/client.py", line 281, in _result
    self._raise_for_status(response)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/Users/toblaroni/Documents/programming/meshtastic/Meshtasticator/venv/lib/python3.13/site-packages/docker/api/client.py", line 277, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/toblaroni/Documents/programming/meshtastic/Meshtasticator/venv/lib/python3.13/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.ImageNotFound: 404 Client Error for http+docker://localhost/v1.47/containers/create?name=Meshtastic: Not Found ("No such image: meshtastic/device-simulator:latest")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/toblaroni/Documents/programming/meshtastic/Meshtasticator/venv/lib/python3.13/site-packages/docker/api/client.py", line 275, in _raise_for_status
    response.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/toblaroni/Documents/programming/meshtastic/Meshtasticator/venv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.47/images/create?tag=latest&fromImage=meshtastic%2Fdevice-simulator

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/toblaroni/Documents/programming/meshtastic/Meshtasticator/interactiveSim.py", line 9, in <module>
    sim = interactiveSim() # Start the simulator
  File "/Users/toblaroni/Documents/programming/meshtastic/Meshtasticator/lib/interactive.py", line 342, in __init__
    self.container = dockerClient.containers.run(DEVICE_SIM_DOCKER_IMAGE, startNode + "-d /home/node"+str(n0.nodeid)+" -h "+str(n0.hwId)+" -p "+str(n0.TCPPort), \
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      ports=dict(zip((str(n.TCPPort)+'/tcp' for n in self.nodes), (n.TCPPort for n in self.nodes))), name="Meshtastic", detach=True, auto_remove=True, user="root")
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/toblaroni/Documents/programming/meshtastic/Meshtasticator/venv/lib/python3.13/site-packages/docker/models/containers.py", line 879, in run
    self.client.images.pull(image, platform=platform)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/toblaroni/Documents/programming/meshtastic/Meshtasticator/venv/lib/python3.13/site-packages/docker/models/images.py", line 464, in pull
    pull_log = self.client.api.pull(
        repository, tag=tag, stream=True, all_tags=all_tags, **kwargs
    )
  File "/Users/toblaroni/Documents/programming/meshtastic/Meshtasticator/venv/lib/python3.13/site-packages/docker/api/image.py", line 429, in pull
    self._raise_for_status(response)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/Users/toblaroni/Documents/programming/meshtastic/Meshtasticator/venv/lib/python3.13/site-packages/docker/api/client.py", line 277, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/toblaroni/Documents/programming/meshtastic/Meshtasticator/venv/lib/python3.13/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.NotFound: 404 Client Error for http+docker://localhost/v1.47/images/create?tag=latest&fromImage=meshtastic%2Fdevice-simulator: Not Found ("no matching manifest for linux/arm64/v8 in the manifest list entries: no match for platform in manifest: not found")```

**Comment by GUVWAF** [comment]
Did you pull the latest changes of the Meshtasticator repository?

**Comment by toblaroni** [comment]
Yeah I pulled the latest changes for meshtasticator and for the firmware.

**Comment by GUVWAF** [comment]
@toblaroni Can you try to add `platform="linux/amd64"` when running the container as suggested in https://github.com/meshtastic/Meshtasticator/issues/22#issuecomment-2633760538?

**Comment by toblaroni** [comment]
Hey, after having a try of this and a poke about, I think the issue is due to the fact i'm trying to run on a Macbook Air M3 which is ARM/V8, which isn't covered by the [Docker builds](https://hub.docker.com/r/meshtastic/meshtasticd).

**Comment by GUVWAF** [comment]
I see, that makes sense. This means that unfortunately it can't be run on the ARM/V8 architecture, but that's beyond the scope of the simulator, so I'll close the issue now.
